spring.application.name=gateway-service

# SERVER
server.port=8080
server.address=0.0.0.0

# ================= EUREKA =================
eureka.client.service-url.defaultZone=https://service-registry-esv4.onrender.com/eureka/
eureka.instance.prefer-ip-address=true

# ================= GATEWAY ROUTES =================
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=quantity-service
spring.cloud.gateway.routes[1].uri=lb://quantity-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/**

spring.cloud.gateway.routes[2].id=history-service
spring.cloud.gateway.routes[2].uri=lb://history-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/history/**

# ================= CORS =================
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

# ================= ACTUATOR =================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.eureka.enabled=false