spring.application.name=gateway-service

server.port=${PORT}
server.address=0.0.0.0

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Eureka
eureka.client.service-url.defaultZone=https://service-registry-esv4.onrender.com/eureka/

# INSTANCE FIX
eureka.instance.hostname=gateway-service-vg52.onrender.com
eureka.instance.prefer-ip-address=false
eureka.instance.secure-port-enabled=true
eureka.instance.non-secure-port-enabled=false

eureka.instance.instance-id=${spring.application.name}:${eureka.instance.hostname}

# HEALTH FIX
eureka.instance.statusPageUrl=https://gateway-service-vg52.onrender.com/actuator/info
eureka.instance.healthCheckUrl=https://gateway-service-vg52.onrender.com/actuator/health

# ACTUATOR
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true