spring.application.name=gateway-service

server.port=${PORT}
server.address=0.0.0.0

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Eureka
eureka.client.service-url.defaultZone=https://service-registry-esv4.onrender.com/eureka/

eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.hostname}

# FIX FOR RENDER (CRITICAL)
eureka.instance.secure-port-enabled=true
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port=443

eureka.instance.status-page-url=https://${RENDER_EXTERNAL_HOSTNAME}/actuator/info
eureka.instance.health-check-url=https://${RENDER_EXTERNAL_HOSTNAME}/actuator/health
eureka.instance.home-page-url=https://${RENDER_EXTERNAL_HOSTNAME}

# ROUTES
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=quantity-service
spring.cloud.gateway.routes[1].uri=lb://quantity-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/**

spring.cloud.gateway.routes[2].id=history-service
spring.cloud.gateway.routes[2].uri=lb://history-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/history/**

# ACTUATOR
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# prevent false DOWN
management.health.eureka.enabled=false